### ISSUE TITLE
Site doesn't exist?

### ISSUE THREAD

**Issue by Zireael07** [rasch/phalanx#1]
Title

**Comment by rasch** [comment]
Hey @Zireael07, thank you for your interest in this keyboard! I finally got around to working on the site but haven't set it up on the server yet. If you still want to check it out, I put a [copy on Netlify](https://zingy-pastelito-1caf93.netlify.app/) and also tagged a [release (v0.1.0)](https://github.com/rasch/phalanx/releases/tag/v0.1.0) so the assets are also available. Thanks!
